### ISSUE TITLE
Hello from the original project owner! :)

### ISSUE THREAD

**Issue by guitarmanvt** [abhinavsingh/django-saml2#1]
Hi! I saw that you've forked my project and uploaded it to PyPI. Great! Now I know that I built something that's useful.

I may do some more maintenance on this at https://github.com/guitarmanvt/django-saml2-sp . You might want to star that repo.

Let's stay in touch.
JSA

**Comment by abhinavsingh** [comment]
Hi John,

Thanks for the message.

Your work was indeed the only working bit I could find back then and was a life saver.  I mostly modified it to work well with Django and PyPI flows.

Unfortunately, I am no longer working with Python/SAML or company for which I forked this, but will sure keep following your work further.

Best,
Abhinav

**Comment by guitarmanvt** [comment]
Hi, Abhinav. It's been a while, and I'm finding that the old google code project is confusing people. Would you be able to do a quick edit on the README and point people to the github repos, please? They are:

https://github.com/guitarmanvt/django-saml2-idp
and 
https://github.com/guitarmanvt/django-saml2-sp

I'm sure it would take just a moment, and it would help people find the right place.

Thanks!

**Comment by abhinavsingh** [comment]
Hi John,

Apologies. I hardly visit Github nowadays. I will be happy to link back to
original project (not sure why and how I missed it).

Cheers.
